import dns from "node:dns/promises";
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import { Outfit } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const OutfitFont = Outfit({
  subsets: ["latin"],
});


export const metadata = {
  title: "Qurbani ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-100">
        <Navber></Navber>
        <main className="container mx-auto ">
          {children}
        </main>
        <Footer></Footer>
        <ToastContainer />
      </body>
    </html>
  );
}
